[package]
name = "pinepods-api"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web Framework
axum = { version = "0.7", features = ["macros", "multipart", "ws"] }
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.4", features = ["util", "timeout", "load-shed", "limit"] }
tower-http = { version = "0.5", features = ["fs", "trace", "cors", "compression-gzip"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "mysql", "uuid", "chrono", "json"] }

# Redis/Valkey
redis = { version = "0.24", features = ["aio", "tokio-comp"] }

# HTTP Client
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }

# Configuration and Environment
config = "0.14"
dotenvy = "0.15"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Utilities
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
thiserror = "1.0"

# Authentication and Crypto
argon2 = "0.5"
jsonwebtoken = "9.0"
rand = "0.8"

# RSS/Feed Processing
feed-rs = "1.3"
url = "2.4"

# Email
lettre = { version = "0.11", default-features = false, features = ["tokio1-rustls-tls", "smtp-transport", "builder"] }

# CORS and Security
hyper = "1.0"

# Background Tasks
tokio-cron-scheduler = "0.10"

# File handling
tokio-util = { version = "0.7", features = ["io"] }
mime_guess = "2.0"

[dev-dependencies]
tower-test = "0.4"